name: build dotnet
on:
  workflow_dispatch:
  schedule:
    - cron: "10 1 * * 1"
  push:
    branches:
      - master
    paths:
      - dotnet/**
jobs:
  push:
    name: "yolks:dotnet_${{ matrix.tag }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        tag:
          - 2.1
          - 3.1
          - 5
          - 6
          - 7
          - 8
          - 9
    steps:
      - uses: actions/checkout@v4
            # Setup QEMU for ARM64 Build
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
        with:
          buildkitd-flags: --debug
      - uses: docker/login-action@v3
        with:
          registry: registry.cn-shanghai.aliyuncs.com
          username: ${{ secrets.REPOSITORY_OWNER }}
          password: ${{ secrets.REGISTRY_TOKEN }}
      - uses: docker/build-push-action@v5
        with:
          context: ./dotnet
          file: ./dotnet/${{ matrix.tag }}/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            registry.cn-shanghai.aliyuncs.com/pterodactyl-images/yolks:dotnet_${{ matrix.tag }}
