name: build go
on:
  workflow_dispatch:
  schedule:
    - cron: "50 1 * * 1"
  push:
    branches:
      - master
    paths:
      - go/**
jobs:
  push:
    name: "yolks:go_${{ matrix.tag }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        tag:
          - '1.14'
          - '1.15'
          - '1.16'
          - '1.17'
          - '1.18'
          - '1.19'
          - '1.20'
          - '1.21'
          - '1.22'
          - '1.23'
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
        with:
          buildkitd-flags: --debug
      - uses: docker/login-action@v3
        with:
          registry: registry.cn-shanghai.aliyuncs.com
          username: ${{ secrets.REPOSITORY_OWNER }}
          password: ${{ secrets.REGISTRY_TOKEN }}
      - uses: docker/build-push-action@v5
        with:
          context: ./go
          file: ./go/${{ matrix.tag }}/Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            registry.cn-shanghai.aliyuncs.com/pterodactyl-images/yolks:go_${{ matrix.tag }}
