name: build mariadb
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  schedule:
    - cron: "20 2 * * 1"
  push:
    branches:
      - master
    paths:
      - mariadb/**
jobs:
  push:
    name: "yolks:mariadb_${{ matrix.tag }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        tag:
          - '10.3'
          - '10.4'
          - '10.5'
          - '10.6'
          - '10.7'
          - '11.2'
          - '11.3'
          - '11.4'
          - '11.5'
          - '11.6'
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
        with:
          buildkitd-flags: --debug
      - uses: docker/login-action@v3
        with:
          registry: registry.cn-shanghai.aliyuncs.com
          username: ${{ secrets.REPOSITORY_OWNER }}
          password: ${{ secrets.REGISTRY_TOKEN }}
      - uses: docker/build-push-action@v5
        with:
          context: ./mariadb
          file: ./mariadb/${{ matrix.tag }}/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            registry.cn-shanghai.aliyuncs.com/pterodactyl-images/yolks:mariadb_${{ matrix.tag }}
